// Generated by Wrangler on Fri Aug 30 2024 11:23:23 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	RELAY_LISTENER_DO: DurableObjectNamespace<import("./src/index").RelayListenerDurableObject>;
	ATPROTO_FIREHOSE_QUEUE: Queue;
}
